const loader=document.getElementById("loader");window.addEventListener("load",()=>setTimeout(()=>loader?.classList.add("hidden"),450));
const dot=document.getElementById("cursorDot"),ring=document.getElementById("cursorRing");let mx=0,my=0,rx=0,ry=0;window.addEventListener("mousemove",e=>{mx=e.clientX;my=e.clientY;if(dot){dot.style.left=mx+"px";dot.style.top=my+"px"}});function cur(){rx+=(mx-rx)*.16;ry+=(my-ry)*.16;if(ring){ring.style.left=rx+"px";ring.style.top=ry+"px"}requestAnimationFrame(cur)}cur();document.querySelectorAll("a,button,.portfolio-card").forEach(el=>{el.addEventListener("mouseenter",()=>{if(ring){ring.style.width="64px";ring.style.height="64px"}});el.addEventListener("mouseleave",()=>{if(ring){ring.style.width="42px";ring.style.height="42px"}})});
const header=document.getElementById("header");window.addEventListener("scroll",()=>header.classList.toggle("scrolled",window.scrollY>45));
const menuBtn=document.getElementById("menuBtn"),mobileMenu=document.getElementById("mobileMenu");menuBtn.addEventListener("click",()=>{menuBtn.classList.toggle("open");mobileMenu.classList.toggle("open")});mobileMenu.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menuBtn.classList.remove("open");mobileMenu.classList.remove("open")}));
const reveals=document.querySelectorAll(".reveal");const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.13});reveals.forEach(x=>ro.observe(x));
const grid=document.getElementById("portfolioGrid"),filters=document.querySelectorAll(".filter"),modal=document.getElementById("modal"),modalCard=document.getElementById("modalCard"),modalClose=document.getElementById("modalClose");
function group(p){if(["Social Media Design","Banner Design"].includes(p.category))return"Design";return p.category}
function ytEmbed(url){try{const u=new URL(url);let id="";if(u.hostname.includes("youtu.be"))id=u.pathname.slice(1);else if(u.pathname.includes("/shorts/"))id=u.pathname.split("/shorts/")[1].split("/")[0];else id=u.searchParams.get("v")||"";return id?`https://www.youtube.com/embed/${id}`:url}catch(e){return url}}
function render(filter="All"){grid.innerHTML="";PROJECTS.filter(p=>filter==="All"||group(p)===filter||p.category===filter).forEach(p=>{const c=document.createElement("article");const layout=p.type==="youtube"?"video":p.layout;c.className=`portfolio-card ${layout} reveal visible`;c.innerHTML=`<div class="media"><img src="${p.thumbnail}" alt="${p.title}"><span class="card-badge">${p.category}</span><span class="card-action">${p.type==="youtube"?"▶":"↗"}</span></div><div class="card-copy"><h3>${p.title}</h3><p>${p.description}</p><small>${p.meta}</small></div>`;c.addEventListener("click",()=>openModal(p));grid.appendChild(c)})}
function openModal(p){let media=p.type==="youtube"?`<iframe src="${ytEmbed(p.media)}" title="${p.title}" allowfullscreen></iframe>`:`<img src="${p.media}" alt="${p.title}">`;modalCard.innerHTML=`${media}<div class="modal-copy"><h3>${p.title}</h3><p>${p.category} • ${p.meta}</p><p>${p.description}</p>${p.type==="youtube"?`<p><a class="btn primary" href="${p.media}" target="_blank">Open on YouTube</a></p>`:""}</div>`;modal.classList.add("open");document.body.classList.add("modal-open")}
function closeModal(){modal.classList.remove("open");document.body.classList.remove("modal-open");modalCard.innerHTML=""}
filters.forEach(b=>b.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)}));modalClose.addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});render();
const img=document.getElementById("showcaseImage"),frame=document.getElementById("showcaseFrame"),title=document.getElementById("slideTitle"),meta=document.getElementById("slideMeta"),num=document.getElementById("slideNumber"),thumbs=document.getElementById("showcaseThumbs"),prev=document.getElementById("prevSlide"),next=document.getElementById("nextSlide");let curSlide=0;
function show(i){if(!DESIGN_SLIDES.length)return;curSlide=(i+DESIGN_SLIDES.length)%DESIGN_SLIDES.length;const s=DESIGN_SLIDES[curSlide];img.style.opacity=0;img.style.transform="scale(1.025)";setTimeout(()=>{frame.classList.remove("square","portrait","landscape","video");frame.classList.add(s.layout);img.src=s.media;title.textContent=s.title;meta.textContent=s.meta;num.textContent=String(curSlide+1).padStart(2,"0");img.style.opacity=1;img.style.transform="scale(1)"},150);document.querySelectorAll(".thumb").forEach((t,j)=>t.classList.toggle("active",j===curSlide))}
DESIGN_SLIDES.forEach((s,i)=>{const b=document.createElement("button");b.className="thumb";b.innerHTML=`<img src="${s.thumbnail}" alt="${s.title}"><span>${s.meta}</span>`;b.addEventListener("click",()=>show(i));thumbs.appendChild(b)});prev.addEventListener("click",()=>show(curSlide-1));next.addEventListener("click",()=>show(curSlide+1));setInterval(()=>show(curSlide+1),4500);show(0);
